### ISSUE TITLE
How to preserve the original numbering when batch-changing the heading levels ？

### ISSUE THREAD

**Issue by Brandern** [k4a-l/obsidian-heading-shifter#13]
I have installed Heading Shift. In order to convert the following numbered headings into level-three headings (H3) all at once:

1. Abstract
2. Method
3. Result
I will select all the headings and use the hotkey cmd+3. While this will convert the headings to H3, the numbering at the beginning will be lost, resulting in:

### Result

May I ask if there is a way to preserve the original numbering in front of the headings?

**Comment by k4a-l** [comment]
In my use case, I often convert lists to headings. So I put in a process to intentionally erase number-list and order-list.
https://github.com/k4a-l/obsidian-heading-shifter/commit/49286e0cba85d7466d74020e32aa03582c6ff30c

But yes, this may be unkind to those who do not.

> May I ask if there is a way to preserve the original numbering in front of the headings?

The answer to this question is 'NO' at the moment, but it seems to make sense to allow this behaviour to be turned on or off in the configuration.

**Comment by Brandern** [comment]
Yes, it would be more convenient if users were allowed to choose whether to preserve the numbering in the settings.

Heading Shifter is really convenient for batch-changing heading levels. Thanks!

**Comment by k4a-l** [comment]
Supported in [1.5.0](https://github.com/k4a-l/obsidian-heading-shifter/releases/tag/1.5.0)

For now, close as completed.
If there are  any bugs or misconceptions, feel free to comment.

**Comment by SpocWeb** [comment]
I use Headings very successfully together with [dynamic, CSS-based Numbering (i.e. not persistent) ](https://github.com/platon-ivanov/obsidian-visually-numbered-headings) 
Dynamic Numberings can be used very well in live Discussions, but not for longer Discussions. 
If you want it persisted, you can use the _Number Headings Plugin_, but beware that re-numbering breaks all your deep Links!
