### ISSUE TITLE
Feature Request: Increase/Decrease headings and subheadings without selection

### ISSUE THREAD

**Issue by cwriasir** [k4a-l/obsidian-heading-shifter#16]
Currently it is only possible to select headings to shift them. I wish there are options to increase and decrease a heading and all its subheadings without needing to select them first.

**Comment by k4a-l** [comment]
I am not sure of the use case.
Do you mean you want a command like "increase all headings for this file"?
In that case, can't I just use "select all" → "increase heading"?
