### ISSUE TITLE
Feature Request: don't override TAB if cursor is on a list

### ISSUE THREAD

**Issue by notuntoward** [k4a-l/obsidian-heading-shifter#17]
Setting  `Enable override tab behavior`  does exactly what it says it does, and I like it.  But also, just like the documentation warns, it interferes with other plugins.  The only one I know of is the outliner plugin, which also uses `TAB`: to indent and outdent lists. 

Would it be possible for heading-shifter to detect when the cursor is on a list, and then not override `TAB` in that case?

For me, at least, this would greatly improve obsidian's overall outlining capabilities.

**Comment by k4a-l** [comment]
The plugin should still only perform the tab behavior on the heading(#) line at present.
I also use outliner and have not had any trouble with it.
What exactly is the behavior?

**Comment by notuntoward** [comment]
Sorry for the false alarm -- I updated and uninstalled a bunch of plugins, and now outliner works perfectly (before, TAB was doing nothing on a bullet).

Tab Shifter is a great plugin.  Thanks!

**Comment by k4a-l** [comment]
I just tried outliner myself.
It seems that the top-level bullet by itself is not indented, regardless of whether it is under a heading or not.

I will close this issue for now, but feel free to let me know if you have any other issues.
