### ISSUE TITLE
Please explain what 'Style to remove' does

### ISSUE THREAD

**Issue by SpocWeb** [k4a-l/obsidian-heading-shifter#18]
Hi, thank you for this Plugin. This allows me to work with Headings as if they were Outliner-Bullets. 
It would be nice if (unlimited) bulleted or numbered Lists were forming a uniform Hierarchy 
together with the (limited) Set of 6 Headings, e.g.
H1 > H2 > ... > H6 > bullet (no indent) > bullet (1 Tab or 2 Spaces) > bullet (2 Tab or 4 Spaces) etc. 

This way nesting/indenting would also indent the Bullets 
and outdenting Bullets would eventually promote them to Headings. 

I originally thought that would be the intention of these Switches: 
![image](https://github.com/k4a-l/obsidian-heading-shifter/assets/10584012/6059bae1-e10f-4cc0-b8a9-61a2e8e23d5c)

to promote the outermost bullet or number to a H6, 
but I actually don't see any effect whether I enable or disable these Toggles 
and try to increase or decrease Headings on a bullet or numbered item. 

Even when I disable the Outliner Pluging, which can of course interfere, I see no effect, 
neither when using the Hotkeys, nor when using the Command Pallette. 

Please explain what these Toggles are supposed to do.
Thank you

**Comment by k4a-l** [comment]
## First, let us explain the meaning of the setting items

This is the toggle between removing or retaining the leading `-` or `1.` when applying Heading in a "single" row.


before
```
- line
```

on
```
## line
```

off
```
## - line
```


## Next, we will review what you want to do

 Do you mean that you want the following bulleted list:
```
- a
	- b
		- c
		- d
			- e
				- f
					- g
						- h
```

 to have the following heading structure in one batch?:
```
# a
## b
### c
### d
#### e
##### f
###### g
- h
```

**Comment by k4a-l** [comment]
If there is a response, reopen.

**Comment by SpocWeb** [comment]
> If there is a response, reopen.

Sorry, I saw this too late... 
Thank you very much for the explanation. Can you please add it to your ReadMe.md so others can easily find them? 

To explain my idea: 
Since we have only 6 Levels of Headings but an unlimited Number of indented List Levels, 
I thought it would be a good idea to tread the first List Level as the 7th Header Level and so on. 
So when you use e.g. Tab to indent , 
- All 6th Level Headings are converted to 1st Level List Items,
- 1st Level List Items are demoted to 2nd Level and so on. 

Similarly when you use Shift-Tab to or outdent
- 1st Level List Items are promoted to Heading 6th Level 
- 2nd Level List Items are promoted to 1st Level
