### ISSUE TITLE
Allow Heading increase from size 0

### ISSUE THREAD

**Issue by apotenza92** [k4a-l/obsidian-heading-shifter#19]
Using Lower limit of heading 0 lets me decrease from # to nothing. I'd like to be able to go from nothing to # and etc. This way I can easily use Increase Headings and Decrease Headings to cycle through all including no heading at all.

**Comment by k4a-l** [comment]
Do you mean you want to be able to use “Increase Headings” instead of “Apply Heading X” to change the heading from 0 to 1?
If so, “Increase Headings” function only targets rows that already have a Heading when selecting multiple rows, so it is difficult to target rows that do not have a Heading (0).
If this is misplaced or you have other ideas, please let us know.

**Comment by apotenza92** [comment]
Apologies if I was unclear. Yes I want to be able to go from no heading at all to a heading by running "Increase Headings". Functionally I want this so I can use the same keyboard shortcuts to shift up / down headings as well as heading / no heading. I assume you're saying this is currently not possible based on how the plugin works?

**Comment by apotenza92** [comment]
Essentially "If there's no heading under the current text and I run increase heading then apply heading 1"

**Comment by k4a-l** [comment]
Yes. Not currently possible, but there are several ways to achieve this.

1. create an option “Include non-heading rows in Increase"
2. create another command “Increase Headings(forced)” and make it work the same as when the option ↑ is set to true
3. if only one row is selected, make the line without headings also be the target of “Increase”.

In the case of 1 and 3, it is troublesome to determine whether lines with list (e.g., -, 1) or other notations should be included, so it is easier to create 2, which is unconditionally included.

By the way, which key do you currently use for “Increase Headings”, “Tab” or another key?

**Comment by apotenza92** [comment]
I use `Control + Command + -` to decrease and `Control + Command + =` to increase. I think it works as ctrl + alt on Windows.

**Comment by apotenza92** [comment]
Hi @k4a-l I have noticed a very minor thing in the usability of this feature.
When I run the shortcut my cursor stays to the left of the inserted ##s. It would be great if your cursor stuck to the right with a space after the ##s so you can just start typing in the heading if I go from 0 headings to anything up.

**Comment by k4a-l** [comment]
fixed
