### ISSUE TITLE
I can't find the command to set hotkey for Increase Headings or Decrease Headings

### ISSUE THREAD

**Issue by SweetGargamel** [k4a-l/obsidian-heading-shifter#23]
As the picture shows ,I have searched the hotkeys  with "head" ,but I can't find the command to set hotkey for Increase Headings or Decrease Headings even change my language into English.
Did I make a mistake?
Thank you for your generous help!
![image](https://github.com/user-attachments/assets/fe152e4e-6b65-4919-ae62-176e03c366d8)

**Comment by k4a-l** [comment]
Is it possible that you just installed the plugin but did not activate it?
Settings > Community plugin > Heading Shifter

**Comment by SweetGargamel** [comment]
Solved.I am sorry I made a mistake.Thanks again!
