### ISSUE TITLE
Feature request: remove bold or italics when applying a heading

### ISSUE THREAD

**Issue by rubcap** [k4a-l/obsidian-heading-shifter#24]
Hi there, thank you for your handy plug-in for Obsidian 💜! Works really well.

It has a lot of features, but there's still one missing that would be very useful: removing bold or italics when applying a heading.

**How it is now**
1. I select a piece of text that has bold° formatting: `**Subtitle within text**`.
2. I use your plug-in to apply a heading style, e.g. H1.
3. Result: `# **Subtitle within text**`

**What I'd like to see**
1. I select a piece of text that has bold° formatting: `**Subtitle within text**`.
2. I use your plug-in to apply a heading style, e.g. H1. "Remove bold" has been activated in the settings.
3. Result: `# Subtitle within text`

(°idem for italics)

The option to remove a style is already there for (un)ordered lists. It would be great to see "remove bold" and "remove italics" there as well! Thank you for taking this into consideration.

**Comment by k4a-l** [comment]
Implemented: #25 
Can you please download the PR resources to see how it works?

If you have any problems or requests, please comment!
If not, we will release it as is.

**Comment by k4a-l** [comment]
released [1.7.0](https://github.com/k4a-l/obsidian-heading-shifter/releases/tag/1.7.0)
