### ISSUE TITLE
"Insert Heading at one level deeper" doesn't remove style  (and documentation request)

### ISSUE THREAD

**Issue by notuntoward** [k4a-l/obsidian-heading-shifter#26]
## Bug
I have ordered and unordered lists set to be removed, as shown below.

This works for the `apply Heading x` commands but not for `Insert Heading at one level deeper`.   For example, if I put the cursor on the list in the example below:

```
# header 1
- list 1
```

The  `Insert Heading at one level deeper` command produces:

```
# header 1
## - list 1
```

## Documentation Request

Could you explain the settings:

- User defined
- Surrounding
   - Bold
   - Italic
   - User Defined

## My Settings

![image](https://github.com/user-attachments/assets/88fa6b5f-610b-40a4-a9d4-8f5cf655081c)

**Comment by k4a-l** [comment]
released [1.7.1](https://github.com/k4a-l/obsidian-heading-shifter/releases/tag/1.7.1)
