### ISSUE TITLE
Feature Request: Insert Heading at current level

### ISSUE THREAD

**Issue by VFUC** [k4a-l/obsidian-heading-shifter#9]
First off: Thanks a lot for creating this plugin, works perfectly 👌 

One feature I would like to use is "inserting a heading at the current level", where the "current level" refers to the last used heading level.

To give an example:

- I start my document with `# A great story` and write some text
- I add a section with `## Chapter One` and write some more
- Now every time I hit the hotkey to "add at current level", I would insert `## Title`
- If I were to add a sub-chapter, e.g. `### Prologue`, adding at the current level would insert a `###`-heading.
- If I then continue with another higher-level heading, e.g. `## Chapter Three`, the current level would be `##` again.

If you were to accept this feature enhancement, I would be happy to open a PR and give this a go myself - just wanted to check beforehand.

Cheers!

**Comment by k4a-l** [comment]
I think it looks very interesting.

"Apply heading" is absolute operations and easy to understand.
But Relative operations of "current-level" is intuitive in another direction.

By the way, how about the concept of "+1 level" , and "-1 level" ?

I would add to the example the following,

- I start my document with `# A great story` and write some text
- I add a section with `## Chapter One` and write some more  `: hit "add +1 level"`
- Now every time I hit the hotkey to "add at current level", I would insert `## Title` 
- If I were to add a sub-chapter, e.g. `### Prologue`,  `: hit "add +1 level"`
- adding at the current level would insert a `###`-heading. 
- If I then continue with another higher-level heading, e.g. `## Chapter Three`, the current level would be `##` again.  `: hit "add -1 level"`

Anyway, PR is welcome!
